This is makeindex, version 2.15 [MiKTeX 20.12].
Scanning style file ./Urban MCM.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Urban MCM.acn....done (272 entries accepted, 0 rejected).
Sorting entries.....done (2388 comparisons).
Generating output file Urban MCM.acr....done (182 lines written, 0 warnings).
Output written in Urban MCM.acr.
Transcript written in Urban MCM.alg.
